require('plugins')
require('keybindings')
require('options')
require('toggleterm-config')
require('lualine-config')
require('bufferline-config')
require('treesitter-config')
require('nvim-tree-config')
require('autopairs-config')
require('whichkey-config')
require('telescope-config')
require('lsp-config')
require('nvim-comment-config')
require('dashboard-config')
require('mymodule')
vim.cmd('colorscheme nord')
vim.cmd('autocmd FileType cpp setlocal commentstring=//%s')

